services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        networks:
            - app
        depends_on:
            - php

    php:
        build: ./images/php
        volumes:
            - ./www:/var/www
        networks:
            - app
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - app

    pma:
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8183:80"
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - app
        depends_on:
            - mysql

networks:
    app:
        driver: bridge
